name: kids_apps2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  bitsdojo_window: ^0.1.6
  supabase_flutter: ^2.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/readcol.png
    - assets/images/mathcol.png
    - assets/gifs/field3.gif
    - assets/sounds/background_music.mp3
    - assets/sounds/error.mp3
    - assets/sounds/click.mp3
    - assets/sounds/a.mp3
    - assets/sounds/b.mp3
    - assets/sounds/c.mp3
    - assets/sounds/d.mp3
    - assets/sounds/e.mp3
    - assets/sounds/f.mp3
    - assets/sounds/g.mp3
    - assets/sounds/h.mp3
    - assets/sounds/i.mp3
    - assets/sounds/j.mp3
    - assets/sounds/k.mp3
    - assets/sounds/l.mp3
    - assets/sounds/m.mp3
    - assets/sounds/n.mp3
    - assets/sounds/o.mp3
    - assets/sounds/p.mp3
    - assets/sounds/q.mp3
    - assets/sounds/r.mp3
    - assets/sounds/s.mp3
    - assets/sounds/t.mp3
    - assets/sounds/u.mp3
    - assets/sounds/v.mp3
    - assets/sounds/w.mp3
    - assets/sounds/x.mp3
    - assets/sounds/y.mp3
    - assets/sounds/z.mp3
    - assets/sounds/perder.mp3
    - assets/sounds/ganador.mp3
    - assets/sounds/bien.mp3
    - assets/sounds/correcto.mp3
    - assets/sounds/mono.mp3
    - assets/sounds/seleccionar.mp3
    - assets/images/read/A-a-r.png
    - assets/images/read/A_de_avion-r.png
    - assets/images/read/escribir_A-r.png
    - assets/images/read/globo-abc-r.png
    - assets/images/read/B_de_bebe-r.png
    - assets/images/read/Cuadros_letras-r.png
    - assets/images/math/0-100-r.png
    - assets/images/math/3_manzanas-r.png
    - assets/images/math/7_dedos-r.png
    - assets/images/math/escribir_1-r.png
    - assets/images/math/globo-uno-r.png
    - assets/images/math/manos-num-r.png
    - assets/images/math/1.png
    - assets/images/math/2.png
    - assets/images/math/3.png
    - assets/images/math/4.png
    - assets/images/math/5.png
    - assets/images/math/6.png
    - assets/images/math/7.png
    - assets/images/math/8.png
    - assets/images/math/9.png
    - assets/images/math/10.png
    